spring.application.name=paymen_steer
server.port= 8077
spring.thymeleaf.cache=false
#payment_steer
paypal.client.id=Ab2wJ9R0jhr0DIjQT94oIqN8V0Z7UiirGMu-SZZ04BZlLwgT7MJXWnAGOuh6sDZMcSauqfuX9rWYKOu5
paypal.client.secret=EJUcv1bktqtSbCiw4zaR5PUWmHK-FZkly6_kfgjna9NGVYuX5AOjd_6pXJ1uXUO3yf0eprBUO0Nn_QzJ
paypal.mode= sandbox